{% set name = "jupyterlab-mathjax3" %}
{% set version = "4.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupyterlab-mathjax3-{{ version }}.tar.gz
  sha256: daee13969453ecfa22ac8969cd1daa8f887731ace8adb93a574b47aecabdc5dd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - jupyter-packaging >=0.7.9,<0.8.0
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - pip check
    - test -f "${PREFIX}/share/jupyter/labextensions/@jupyterlab/mathjax3-extension/package.json"                                    # [unix]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\@jupyterlab\\mathjax3-extension\\package.json (exit 0) else (exit 1)         # [win]
  requires:
    - pip

about:
  home: https://github.com/jupyterlab/jupyter-renderers
  summary: MathJax 3 math renderer for JupyterLab
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jtpio
    - jasongrout
    - blink1073
